AWSTemplateFormatVersion: 2010-09-09
Description: Lambda
Resources:
  indexPhoto:
    Type: 'AWS::Lambda::Function'
    Properties:
      Code:
        S3Bucket: codebucket-jx2467
        S3Key: index-photos.zip
      Description: Lambda function
      MemorySize: 128
      Environment:
        Variables:
          REGION: us-east-1
      Handler: indexPhotoFunctional.lambda_handler
      Role: 'arn:aws:iam::414199463068:role/cloudformation-role'
      Timeout: 30
      Runtime: python3.9
      FunctionName: indexPhotoFunctional
  searchPhotos:
    Type: 'AWS::Lambda::Function'
    Properties:
      Code:
        S3Bucket: codebucket-jx2467
        S3Key: search-photos.zip
      Description: Lambda function for CD Demo
      MemorySize: 128
      Environment:
        Variables:
          REGION: us-east-1
      Handler: searchPhotosFunctional.lambda_handler
      Role: 'arn:aws:iam::414199463068:role/cloudformation-role'
      Timeout: 30
      Runtime: python3.9
      FunctionName: searchPhotosFunctional
  ServerlessRestApiDeploymentb2888a1f04:
    Type: 'AWS::ApiGateway::Deployment'
    Properties:
      RestApiId: !Ref ServerlessRestApi
      Description: RestApi deployment
      StageName: Stage
  ServerlessRestApi:
    Type: 'AWS::ApiGateway::RestApi'
    Properties:
      Body:
        info:
          version: '1.0'
          title: !Ref 'AWS::StackName'
        paths:
          /search-photos:
            get:
              x-amazon-apigateway-integration:
                httpMethod: POST
                type: aws_proxy
                uri: !Sub >-
                  arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${searchPhotos.Arn}/invocations
              responses: {}
          /upload-photos:
            put:
              x-amazon-apigateway-integration:
                httpMethod: POST
                type: aws_proxy
                uri: !Sub >-
                  arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${searchPhotos.Arn}/invocations
              responses: {}
        swagger: '2.0'
  searchPhotosLambdaAPIPermissionProd:
    Type: 'AWS::Lambda::Permission'
    Properties:
      Action: 'lambda:InvokeFunction'
      Principal: apigateway.amazonaws.com
      FunctionName: !Ref searchPhotos
      SourceArn: !Sub
        - >-
          arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${__ApiId__}/${__Stage__}/GET/search-photos
        - __Stage__: '*'
          __ApiId__: !Ref ServerlessRestApi
  photosBucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: ccbd-assignment2-photos-bucket
  ESInstance:
    Type: 'AWS::OpenSearchService::Domain'
    Properties:
      DomainName: es-photos
      ClusterConfig:
        InstanceType: t3.small.search
        InstanceCount: 1
      EBSOptions:
        EBSEnabled: True
        VolumeType: gp2
        VolumeSize: 10
