AWSTemplateFormatVersion: "2010-09-09"
Transform: "AWS::Serverless-2016-10-31"
Description: CD Demo Lambda
Resources:
  searchphotos:
    Type: "AWS::Serverless::Function"
    Properties:
      FunctionName: search-photos-2
      Handler: lambda_function.lambda_handler
      Runtime: python3.6
      CodeUri: ./search-photos
      Description: "Lambda function for CD Demo"
      MemorySize: 128
      Timeout: 30
      Role: "arn:aws:iam::414199463068:role/cloudformation-role"
      Environment:
        Variables:
          REGION: us-east-1
  indexphotos:
    Type: "AWS::Serverless::Function"
    Properties:
      FunctionName: index-photos-2
      Handler: lambda_function.lambda_handler
      Runtime: python3.6
      CodeUri: ./index-photos
      Description: "Lambda function for CD Demo"
      MemorySize: 128
      Timeout: 30
      Role: "arn:aws:iam::414199463068:role/cloudformation-role"
      Environment:
        Variables:
          REGION: us-east-1